application:
  baseUrl: ${ORDER_BASE_URL}
  housekeeping:
    payment-create: "0 * * * * *" # every minute

graphql:
  servlet:
    mapping: /graphql
    corsEnabled: false
    exception-handlers-enabled: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    base-path: /
  enabled: true
  pageTitle: Order GraphiQL

logging:
  level:
    .: INFO
    de.florianbeetz: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG


server:
  servlet:
    context-path: /order

spring:
  datasource:
    url: jdbc:postgresql://${ORDER_DB_HOST}:${ORDER_DB_PORT}/${ORDER_DB_DATABASE}
    username: ${ORDER_DB_USER}
    password: ${ORDER_DB_PASSWORD}
  jpa:
    generate-ddl: true
  
keycloak:
  realm: ma-graphql-shop
  auth-server-url: ${ORDER_AUTH_URL:http://localhost/auth} # default value required for testing
  ssl-required: none
  resource: ${ORDER_AUTH_CLIENT}
  credentials:
    secret: ${ORDER_AUTH_SECRET}
  use-resource-role-mappings: true
  bearer-only: true