graphql:
  servlet:
    mapping: /graphql
    corsEnabled: false
    exception-handlers-enabled: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    base-path: /
  enabled: true
  pageTitle: Inventory GraphiQL
  
logging:
  level:
    root: INFO
    de.florianbeetz: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.security: DEBUG


server:
  servlet:
    context-path: /inventory

spring:
  datasource:
    url: jdbc:postgresql://${INVENTORY_DB_HOST}:${INVENTORY_DB_PORT}/${INVENTORY_DB_DATABASE}
    username: ${INVENTORY_DB_USER}
    password: ${INVENTORY_DB_PASSWORD}
  jpa:
    generate-ddl: true

keycloak:
  realm: ma-graphql-shop
  auth-server-url: ${INVENTORY_AUTH_URL:http://localhost/auth} # default value required for testing
  ssl-required: none
  resource: ${INVENTORY_AUTH_CLIENT}
  credentials:
    secret: ${INVENTORY_AUTH_SECRET}
  use-resource-role-mappings: true
  bearer-only: true